### ISSUE TITLE
Can't submit diff: JSON parse error

### ISSUE THREAD

**Issue by tautschnig** [amzn/oss-contribution-tracker#21]
I have previously submitted successfully a number of diffs, but I am now getting:
"An error occurred while processing your diff: JSON.parse: unexpected character at line 1 column 1 of the JSON data"

As I didn't submit JSON in the first place, there isn't really very much that I, as a user, can do in response to this error message. Please let me know if I can provide any further input to help debug this.

**Comment by jpeddicord** [comment]
Hey Michael,

I'll open a ticket internally about this & CC you -- you're seeing an Amazon-specific bug with a recent deployment.
